# Generated by Django 4.2.1 on 2023-05-07 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_alter_invoice_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="date_paid",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 7, 19, 50, 11, 754195)
            ),
        ),
    ]
