# Generated by Django 4.2.1 on 2023-05-07 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("corecode", "0005_scheme"),
        ("students", "0002_auto_20201124_0614"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["enrollment_number"]},
        ),
        migrations.RenameField(
            model_name="student",
            old_name="current_class",
            new_name="course",
        ),
        migrations.RemoveField(
            model_name="student",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="student",
            name="other_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="surname",
        ),
        migrations.AddField(
            model_name="student",
            name="Source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="corecode.scheme",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="Total_fee",
            field=models.IntegerField(default=0, verbose_name="Total Fees"),
        ),
        migrations.AddField(
            model_name="student",
            name="aadhar_no",
            field=models.IntegerField(default=None, verbose_name="Aadhar Card Number"),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="Father's/Husband's Name",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_occ",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="Father's/Husband's Occupation",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="Mother's Name",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(
                default=None, max_length=200, verbose_name="Student Name"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_community",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OC", "OC"),
                    ("BC", "BC"),
                    ("MBC", "MBC"),
                    ("ST/SC", "ST/SC"),
                    ("Others", "Others"),
                ],
                default=None,
                max_length=500,
                null=True,
                verbose_name="Student Community",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_company",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="Company Name",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_occupation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Student", "Student"),
                    ("House Wife", "House Wife"),
                    ("Employed", "Employed"),
                    ("Unemployed", "Unemployed"),
                    ("Business", "Business"),
                    ("others", "others"),
                ],
                default=None,
                max_length=200,
                null=True,
                verbose_name="Student Occupation",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_qulaification",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="Student Qualification",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_religion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HINDU", "HINDU"),
                    ("MUSLIM", "MUSLIM"),
                    ("Christian", "Christian"),
                    ("OTHERS", "OTHERS"),
                ],
                default=None,
                max_length=500,
                null=True,
                verbose_name="Student Religion",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("Discontinued", "Discontinued"),
                    ("Break", "break"),
                    ("Long Absent", "Long Absent"),
                ],
                default="active",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrollment_number",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Enrollment Number"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="parent_mobile_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered mobile number isn't in a right format!",
                        regex="^[0-9]{10,15}$",
                    )
                ],
                verbose_name="Mobile Number",
            ),
        ),
    ]
