# Generated by Django 4.2.1 on 2023-05-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corecode", "0004_auto_20201124_0614"),
    ]

    operations = [
        migrations.CreateModel(
            name="scheme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
